<a href="https://colab.research.google.com/github/MaksBreus/Maksym-Breusov.amazinumtask/blob/task1-Pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
energy = pd.read_excel('Energy Indicators.xls', skiprows=17, skipfooter=38)

energy = energy.drop(energy.columns[[0, 1]], axis=1)

energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
energy.replace('...', np.nan, inplace=True)

energy['Energy Supply'] = energy['Energy Supply'] * 1000000
energy['Country'] = energy['Country'].str.replace(r'\d+', '', regex=True)
energy['Country'] = energy['Country'].str.replace(r' \(.*\)', '', regex=True)
energy['Country'] = energy['Country'].str.strip()

dict_names = {
    "Republic of Korea": "South Korea",
    "United States of America": "United States",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "China, Hong Kong Special Administrative Region": "Hong Kong"
}
energy['Country'] = energy['Country'].replace(dict_names)

/tmp/ipykernel_4859/3408984409.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  energy.replace('...', np.nan, inplace=True)

In [ ]:
gdp = pd.read_excel('world_bank.xls', skiprows=4)
gdp.rename(columns={gdp.columns[0]: 'Country Name'}, inplace=True)

gdp_names = {
    "Korea, Rep.": "South Korea",
    "Iran, Islamic Rep.": "Iran",
    "Hong Kong SAR, China": "Hong Kong"
}
gdp['Country Name'] = gdp['Country Name'].replace(gdp_names)
gdp = pd.concat([gdp.iloc[:, [0]], gdp.iloc[:, -10:]], axis=1)

gdp.columns = ['Country Name', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
gdp.head()

,Country Name,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Africa Eastern and Southern,9.859871e+11,1.006526e+12,9.273485e+11,8.851764e+11,1.021043e+12,1.007196e+12,1.000834e+12,9.275933e+11,1.081998e+12,1.169484e+12
1,Afghanistan,2.056449e+10,2.055058e+10,1.999814e+10,1.801955e+10,1.889635e+10,1.841886e+10,1.890450e+10,2.014345e+10,1.458314e+10,NaN
2,Africa Western and Central,8.339481e+11,8.943225e+11,7.686447e+11,6.913634e+11,6.848988e+11,7.670257e+11,8.225384e+11,7.864600e+11,8.444597e+11,8.778633e+11
3,Angola,1.334016e+11,1.372444e+11,8.721930e+10,4.984049e+10,6.897277e+10,7.779294e+10,6.930911e+10,5.024137e+10,6.568544e+10,1.067136e+11
4,Albania,1.277622e+10,1.322815e+10,1.138685e+10,1.186120e+10,1.301973e+10,1.515642e+10,1.540183e+10,1.516273e+10,1.793057e+10,1.888210e+10

In [ ]:
ScimEn = pd.read_excel('scimagojr.xlsx')

df = pd.merge(ScimEn, energy, how='inner', on='Country')
df = pd.merge(df, gdp, how='inner', left_on='Country', right_on='Country Name')
df = df.set_index('Country')

Top15 = df.sort_values('Rank').head(15)
Top15 = Top15.drop('Country Name', axis=1)
Top15

,Rank,Region,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,,
China,1,Asiatic Region,273437,272374,2336764,1615239,8.55,245,1.271910e+11,93.0,...,9.570471e+12,1.047562e+13,1.106157e+13,1.123331e+13,1.231049e+13,1.389491e+13,1.427997e+13,1.468774e+13,1.782046e+13,1.796317e+13
United States,2,Northern America,175891,172431,2230544,724472,12.68,363,9.083800e+10,286.0,...,1.684319e+13,1.755068e+13,1.820602e+13,1.869511e+13,1.947734e+13,2.053306e+13,2.138098e+13,2.106047e+13,2.331508e+13,2.546270e+13
India,3,Asiatic Region,55082,53775,463165,162944,8.41,181,3.319500e+10,26.0,...,1.856721e+12,2.039126e+12,2.103588e+12,2.294797e+12,2.651474e+12,2.702930e+12,2.835606e+12,2.671595e+12,3.150307e+12,3.385090e+12
Japan,4,Asiatic Region,50523,50065,488062,119930,9.66,193,1.898400e+10,149.0,...,5.212328e+12,4.896994e+12,4.444931e+12,5.003678e+12,4.930837e+12,5.040881e+12,5.117994e+12,5.048790e+12,5.005537e+12,4.231141e+12
United Kingdom,5,Western Europe,43389,42284,615670,111290,14.19,226,7.920000e+09,124.0,...,2.786315e+12,3.065223e+12,2.934858e+12,2.699660e+12,2.683489e+12,2.878152e+12,2.857058e+12,2.704609e+12,3.122480e+12,3.070668e+12
Germany,6,Western Europe,38739,38013,433148,95145,11.18,196,1.326100e+10,165.0,...,3.733805e+12,3.889093e+12,3.357586e+12,3.469853e+12,3.690849e+12,3.974443e+12,3.888226e+12,3.889669e+12,4.259935e+12,4.072192e+12
Russian Federation,7,Eastern Europe,36735,36560,115938,54993,3.16,90,3.070900e+10,214.0,...,2.292470e+12,2.059242e+12,1.363482e+12,1.276786e+12,1.574199e+12,1.657329e+12,1.693115e+12,1.493076e+12,1.836892e+12,2.240422e+12
Canada,8,Northern America,33472,32863,568080,100953,16.97,227,1.043100e+10,296.0,...,1.846597e+12,1.805750e+12,1.556509e+12,1.527995e+12,1.649266e+12,1.725298e+12,1.743725e+12,1.647598e+12,2.001487e+12,2.139840e+12
Italy,9,Western Europe,27983,26940,352993,87828,12.61,166,6.530000e+09,109.0,...,2.141924e+12,2.162010e+12,1.836638e+12,1.877072e+12,1.961796e+12,2.091932e+12,2.011302e+12,1.897210e+12,2.114356e+12,2.010432e+12
South Korea,10,Asiatic Region,27655,27445,328488,61531,11.88,155,1.100700e+10,221.0,...,1.370795e+12,1.484318e+12,1.465773e+12,1.500112e+12,1.623901e+12,1.724846e+12,1.651423e+12,1.644313e+12,1.810956e+12,1.665246e+12
France,11,Western Europe,25232,24732,343860,65734,13.63,178,1.059700e+10,166.0,...,2.811877e+12,2.855964e+12,2.439189e+12,2.472964e+12,2.595151e+12,2.790957e+12,2.728870e+12,2.639009e+12,2.957880e+12,2.782905e+12
Iran,12,Middle East,22933,22734,307280,97038,13.40,141,9.172000e+09,119.0,...,4.927756e+11,4.603828e+11,4.082129e+11,4.579546e+11,4.866301e+11,3.279007e+11,2.836495e+11,2.397355e+11,3.590969e+11,3.885445e+11
Spain,13,Western Europe,21955,21597,352497,64588,16.06,176,4.923000e+09,106.0,...,1.355580e+12,1.371821e+12,1.196157e+12,1.233555e+12,1.313245e+12,1.421703e+12,1.394320e+12,1.276963e+12,1.427381e+12,1.397509e+12
Brazil,14,Latin America,21524,21236,183915,45172,8.54,127,1.214900e+10,59.0,...,2.472819e+12,2.456044e+12,1.802212e+12,1.795693e+12,2.063515e+12,1.916934e+12,1.873288e+12,1.476107e+12,1.649623e+12,1.920096e+12
Australia,15,Pacific Region,20614,20147,314307,51583,15.25,176,5.386000e+09,231.0,...,1.576330e+12,1.467590e+12,1.350580e+12,1.206563e+12,1.326467e+12,1.428267e+12,1.392219e+12,1.326945e+12,1.552703e+12,1.675419e+12

In [ ]:
years = ['2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
avgGDP = Top15[years].mean(axis=1).sort_values(ascending=False)
avgGDP

Country
United States         2.025246e+13
China                 1.332977e+13
Japan                 4.893311e+12
Germany               3.822565e+12
United Kingdom        2.880251e+12
France                2.707477e+12
India                 2.569124e+12
Italy                 2.010467e+12
Brazil                1.942633e+12
Canada                1.764406e+12
Russian Federation    1.748701e+12
South Korea           1.594168e+12
Australia             1.430308e+12
Spain                 1.338823e+12
Iran                  3.904883e+11
dtype: float64

In [ ]:
Top15['Ratio'] = Top15['Self-citations'] / Top15['Citations']

max_country = Top15['Ratio'].idxmax()
max_value = Top15['Ratio'].max()

print(max_country, max_value)

China 0.6912289816173135

In [ ]:
def answer_three():
    target = avgGDP.index[5]

    res = Top15.loc[target]['2015'] - Top15.loc[target]['2006']
    return res

answer_three()

np.float64(-28971577704.52539)

In [ ]:
Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']

third_pop = Top15['Population'].sort_values(ascending=False).index[2]
third_pop

'United States'

In [ ]:
Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['Population']

correlation = Top15['Citable docs per Capita'].corr(Top15['Energy Supply per Capita'])
correlation

np.float64(0.7434709127726777)

In [ ]:
ContinentDict  = {'China':'Asia', 'United States':'North America', 'Japan':'Asia',
                  'United Kingdom':'Europe', 'Russian Federation':'Europe', 'Canada':'North America',
                  'Germany':'Europe', 'India':'Asia', 'France':'Europe', 'South Korea':'Asia',
                  'Italy':'Europe', 'Spain':'Europe', 'Iran':'Asia', 'Australia':'Australia',
                  'Brazil':'South America'}

Top15['Continent'] = pd.Series(ContinentDict)

ans_seven = Top15.groupby('Continent')['Population'].agg(['size', 'sum', 'mean', 'std'])
ans_seven

               size           sum          mean           std
Continent
Asia              5  2.898666e+09  5.797333e+08  6.790979e+08
Australia         1  2.331602e+07  2.331602e+07           NaN
Europe            6  4.579297e+08  7.632161e+07  3.464767e+07
North America     2  3.528552e+08  1.764276e+08  1.996696e+08
South America     1  2.059153e+08  2.059153e+08           NaN